Massive Update for storage model
CS2103-AY1819S2-W13-3/main pull request #54
Opened 2019-03-02 16:04 UTC by DarrenDragonLee

Added 3 files to handle source storage function.

Source object will be the primary type for storing source information. Contains the following fields. More can be added as necessary.
1) Source Title (compulsory field)
2) Source Type (compulsory field)
3) Source Details (compulsory field)
4) Source Tags (can contain 0 or more tags)

Functions should be able to accomplish the following:
1) Add a new source to the database of sources
2) Delete sources from the database by index
3) Mass delete all sources from the database
4) Load existing database from an external txt file
5) Write current database to external txt file
6) Edit the each of the parameters in each source individually and by index

#51

2019-03-02 16:05 UTC, DarrenDragonLee commented
Pending review

2019-03-02 16:56 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/Source.java
> +    /** Title of the source as detailed by the user, can be anything **/
To be consistent in styling, it should be `/** comment */`, and not `/** comment **/`. Also, it's more appropriate to use single line comments (`//`) rather than multi-line comments to comment on variables.

2019-03-02 16:56 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/Source.java
> +    /** Public get functions for all the details of the source, to be used for retrieving information **/
This is not the Javadoc comment format :( Check out the style guide: https://nus-cs2103-ay1819s2.github.io/cs2103-website/coding-standards/java/intermediate.html#comments

You don't have to state it's public too, cause you already used the `public` access modifier keyword 😛

2019-03-02 16:56 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceDatabase.java
> +    // Constructor for the main database object, will automatically load any existing entries in the database file
Multiline comment in Javadoc format is more appropriate here

2019-03-02 16:56 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceDatabase.java
> +    // The database will be empty otherwise
Same for this and line 15 too

2019-03-02 16:56 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceStorageOperations.java
> +    // File path for database text file
Eh, no need to comment if it's super obvious from your variable name already haha

2019-03-02 16:56 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceStorageOperations.java
> +            System.out.println("Error loading file.");
Use logger instead of println

2019-03-02 17:00 UTC, case141 requested changes
I think we should create it similar to how the persons model is created and not just one whole sourcemodel. Because this may cause problems in the future code. You should add the individual title/tag/type/detail classes. Should be done as soon as possible in future versions.

2019-03-02 17:21 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceDatabase.java
> +        this.database.add(sourceToAdd);
No need for `this.` if it's unambiguous (i.e. no conflicting variable name in scope). I think this is part of the style guide.

2019-03-02 17:22 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceStorageOperations.java
> +        ArrayList<Source> decodedSources = new ArrayList<Source>();
Should we use type inference and standardize across the project? @case141

2019-03-02 17:27 UTC, case141 commented on src/main/java/seedu/address/sourcemodel/SourceStorageOperations.java
> +        ArrayList<Source> decodedSources = new ArrayList<Source>();
not necessary

2019-03-02 18:23 UTC, DarrenDragonLee commented
Modified the Java Docs accordingly and a few minor changes

2019-03-03 01:43 UTC, fterh requested changes

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/Source.java
> +    // Title of the source as detailed by the user, can be anything
You don't need to comment if your variable name is descriptive, e.g. sourceTitle is obvious enough

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/Source.java
>      private String sourceType;
This should be an enumeration

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/Source.java
> +    // List of tags for this source, while user defined, should follow some conventions to avoid duplicates
Why not use a HashSet to avoid duplicates?

Also you might wanna consider canonicalizing them, e.g. strip whitespaces and lowercase them, so you won't end up with e.g. "Biology" and "biology".

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/Source.java
> +    /**
Not 100% sure about this, but I'm pretty sure (99%) this gets interpreted as javadoc comment for `getSourceTitle()`, so if you try to use getSourceTitle() IntelliJ will pop up with the description "Public get functions for all the details of the source, to be used for retrieving information".

Have you tried this?

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/Source.java
> +    /**
Same

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceDatabase.java
> +    /**
Same as prev

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceDatabase.java
>          this.database = SourceStorageOperations.loadExistingDatabase();
You forgot to remove this `this.` :P

2019-03-03 01:43 UTC, fterh commented on src/main/java/seedu/address/sourcemodel/SourceDatabase.java
> +        database.get(index).setSourceTitle(newTitle);
Eh, `database.get(index)` potentially throws `IndexOutOfBoundsException`. I think you should wrap it in a try catch clause to fail gracefully (maybe log it and feedback to user), otherwise the whole program will just crash :P

2019-03-03 04:12 UTC, fterh approved these changes

2019-03-03 04:59 UTC, case141 approved these changes

2019-03-03 05:26 UTC, merged